output "environment_id" {
  description = "Confluent Environment ID"
  value       = confluent_environment.staging.id
}

output "kafka_cluster_id" {
  description = "Kafka Cluster ID"
  value       = confluent_kafka_cluster.standard.id
}

output "kafka_bootstrap_servers" {
  description = "Kafka Bootstrap Servers"
  value       = confluent_kafka_cluster.standard.bootstrap_endpoint
}

output "kafka_rest_endpoint" {
  description = "Kafka REST Endpoint"
  value       = confluent_kafka_cluster.standard.rest_endpoint
}

output "schema_registry_url" {
  description = "Schema Registry URL"
  value       = data.confluent_schema_registry_cluster.sr-cluster.rest_endpoint
}

output "schema_registry_id" {
  description = "Schema Registry Cluster ID"
  value       = data.confluent_schema_registry_cluster.sr-cluster.id
}

output "flink_compute_pool_id" {
  description = "Flink Compute Pool ID"
  value       = confluent_flink_compute_pool.flinkpool-main.id
}

output "service_account_id" {
  description = "Service Account ID"
  value       = confluent_service_account.app-manager.id
}

output "kafka_api_key" {
  description = "Kafka API Key"
  value       = confluent_api_key.app-manager-kafka-api-key.id
  sensitive   = true
}

output "kafka_api_secret" {
  description = "Kafka API Secret"
  value       = confluent_api_key.app-manager-kafka-api-key.secret
  sensitive   = true
}

output "sr_api_key" {
  description = "Schema Registry API Key"
  value       = confluent_api_key.app-manager-schema-registry-api-key.id
  sensitive   = true
}

output "sr_api_secret" {
  description = "Schema Registry API Secret"
  value       = confluent_api_key.app-manager-schema-registry-api-key.secret
  sensitive   = true
}

output "flink_api_key" {
  description = "Flink API Key"
  value       = confluent_api_key.app-manager-flink-api-key.id
  sensitive   = true
}

output "flink_api_secret" {
  description = "Flink API Secret"
  value       = confluent_api_key.app-manager-flink-api-key.secret
  sensitive   = true
}

output "connection_info" {
  description = "Connection information for local Docker environment"
  value = <<-EOT

==============================
   CONFLUENT CLOUD CONNECTION INFO
==============================
Environment ID:         ${confluent_environment.staging.id}
Kafka Cluster ID:       ${confluent_kafka_cluster.standard.id}
Flink Compute Pool ID:  ${confluent_flink_compute_pool.flinkpool-main.id}

Bootstrap Servers:      ${confluent_kafka_cluster.standard.bootstrap_endpoint}
Schema Registry URL:    ${data.confluent_schema_registry_cluster.sr-cluster.rest_endpoint}

Kafka API Key:          ${confluent_api_key.app-manager-kafka-api-key.id}
Kafka API Secret:       ${confluent_api_key.app-manager-kafka-api-key.secret}

SR API Key:             ${confluent_api_key.app-manager-schema-registry-api-key.id}
SR API Secret:          ${confluent_api_key.app-manager-schema-registry-api-key.secret}

Flink API Key:          ${confluent_api_key.app-manager-flink-api-key.id}
Flink API Secret:       ${confluent_api_key.app-manager-flink-api-key.secret}

==============================
   NEXT STEPS
==============================
1. The .env.local file has been automatically generated in the project root
2. Start Docker environment:
   cd ..
   docker-compose -f docker-compose.local.yml --env-file .env.local up -d
3. Register Debezium connector:
   ./scripts/register-debezium-connector.sh

  EOT
  sensitive = true
}

# Generate .env.local file automatically
resource "local_file" "env_local" {
  filename = "../.env.local"
  content  = <<-EOT
# Confluent Cloud Connection Information
# Auto-generated by Terraform - DO NOT EDIT MANUALLY

# Kafka Bootstrap Servers (protocol prefix removed for Debezium Connect)
BOOTSTRAP_SERVERS=${replace(confluent_kafka_cluster.standard.bootstrap_endpoint, "SASL_SSL://", "")}

# Kafka API Credentials
KAFKA_API_KEY=${confluent_api_key.app-manager-kafka-api-key.id}
KAFKA_API_SECRET=${confluent_api_key.app-manager-kafka-api-key.secret}

# Schema Registry
SCHEMA_REGISTRY_URL=${data.confluent_schema_registry_cluster.sr-cluster.rest_endpoint}
SR_API_KEY=${confluent_api_key.app-manager-schema-registry-api-key.id}
SR_API_SECRET=${confluent_api_key.app-manager-schema-registry-api-key.secret}
  EOT
  
  depends_on = [
    confluent_api_key.app-manager-kafka-api-key,
    confluent_api_key.app-manager-schema-registry-api-key
  ]
}